### ISSUE TITLE
Complier issue

### ISSUE THREAD

**Issue by x1aox1AmI** [googleprojectzero/bochspwn-reloaded#3]
I try to complier bochspwn, but there is an issue in symbols.h

issue code:
#include "DbgHelp.h"

In file included from instrument.cc:35:0:
symbols.h:24:21: fatal error: DbgHelp.h: No such file or directory

**Comment by j00ru** [comment]
Similarly to the DbgHelp library (`dbghelp.lib` or `dbghelp.dll`), the `DbgHelp.h` header file is not distributed with Bochspwn and must be manually copied to the instrumentation directory from Microsoft SDK before compilation. I clarified this in the build instructions (commit c6f81c751c004cecb1416409856d65e9ce8b7f9f). I hope that helps!
