### ISSUE TITLE
Multiprocessor Specification question.

### ISSUE THREAD

**Issue by xinali** [googleprojectzero/bochspwn-reloaded#7]
I compiled bochs without `--enable-smp`, I found its speed was very slow.
So I want ot ask if I compile boshc with `--enable-smp`, it will affect my fuzz program result or not?

**Comment by j00ru** [comment]
What exactly do you mean by very slow? Bochs as a software emulator is very slow by definition, guest execution speeds around 50-150M IPS are expected.

I have never used `--enable-smp` so it's hard for me to comment on how it will affect the performance, but according to the documentation:

`Do not expect this option to speed up your simulation! On the contrary, it has to spend extra time simulating the different CPUs (even if they're mostly idle) and the communication between them.`

So I would advise against enabling SMP.

**Comment by xinali** [comment]
OK, I see. Thanks.
